@startuml addFriend
!theme vibrant from https://raw.githubusercontent.com/plantuml/plantuml/master/themes
autonumber


actor Bob as User
database ClientDB
participant Client
queue SessionQueue
participant  Session
queue ServerQueue
participant Server
database ServerDB

User -> Client : addFriend(Alice)
Client -> ClientDB : getFriendList()
Client -> Client : checkFriendList(Alice)
alt Already friend
    Client -> Client : displayAlreadyFriend()
else Not friend
    Client -> SessionQueue : msgsnd(addFriendRequest(Alice) )
    SessionQueue -> Session : msgrcv()
    Session -> Session : change msg access rights()
    Session -> SessionQueue : msgsnd(addFriendRequest(Alice) )



end




@enduml
