@startjson clientDB
!theme vibrant from https://raw.githubusercontent.com/plantuml/plantuml/master/themes

{
    "PrivateKey": "char[1000]",
    "Messages":[
        {
        "name": "id",
        "type": "int",
        "pk": true
        },
        {
        "name": "type",
        "type": "int"
        },
        {
        "name": "sender",
        "type": "int",
        "fk": "Server.User.id"
        },
        {
        "name": "receiver",
        "type": "int",
        "fk": "Server.User.id"
        },
        {
        "name": "message",
        "type": "char[1000]"
        },
        {
        "name": "time",
        "type": "char[20]"
        }
    ],
    "Friends": [
        {
    "name": "id",
    "type": "int",
    "fk": "Server.Users.id"
        },
        {
    "name": "publicKey",
    "type": "char[1000]"
        }
    ],
    "Groups": [
        {
        "name": "id",
        "type": "int",
        "fk": "Server.Groups.id"
        },
        {
        "name": "publicKey",
        "type": "char[1000]"
        },
        {
        "name": "privateKey",
        "type": "char[1000]"
        }
    ]
}
@endjson
