@startuml createGroup
!theme vibrant from https://raw.githubusercontent.com/plantuml/plantuml/master/themes
autonumber


actor Bob as User
database ClientDB
participant Client
queue SessionQueue
participant  Session
queue ServerQueue
participant Server
database ServerDB

User -> Client : Create Group Request
Client -> ClientDB : Validate Request
alt Already in this group
    ClientDB --> Client : Error
else Not in this group
    ClientDB --> Client : Success
    Client -> SessionQueue : Create Group Request
    SessionQueue -> Session : Create Group Request
    Session -> ServerQueue : Create Group Request
    ServerQueue -> Server : Create Group Request
    Server <-> ServerDB : Check if group exists
    alt Group exists
        ServerDB --> Server : Error
        Server -> SessionQueue : Create Group Response
        SessionQueue --> Session : Create Group Response
        Session -> Session: Change access level
        Session -> SessionQueue : Create Group Response
        SessionQueue --> Client :  Response
        Client -> Client : show(Error)
        Client -> User : show(Error)
    else Group does not exist
        ServerDB --> Server : Success
        Server -> ServerDB : Create Group
        ServerDB --> Server : Success
        Server -> ServerQueue : Create Group Response
        ServerQueue --> Session : Create Group Response
        Session -> SessionQueue : Create Group Response
        SessionQueue --> Client : Create Group Response
        Client -> ClientDB : Create Group
        ClientDB --> Client : Success
        Client -> Client : show(Success)
        Client -> User : show(Success)
    end

end



@enduml
