@startuml establishConnection
!theme vibrant from https://raw.githubusercontent.com/plantuml/plantuml/master/themes

actor Bob as User order 1
database ClientDB as ClientDB order 2
database ServerDB as ServerDB order 30

autonumber

== Server Initialization ==
' Server initialization
create Server order 25
ServerDB <->o Server : load_db()
activate Server
create queue ServerQueue order 24
Server ->o ServerQueue : msgget('server', IPC_CREAT)
activate ServerQueue

== Client Initialization ==
' Client initialization
create Client order 3
User -> Client : login(login,password)
activate Client
create queue ClientQueue order 4
Client -> ClientQueue : msgget(client_key, IPC_CREAT)
activate ClientQueue
Client -> ServerQueue : msgget('server')
alt Failure connection to server
    loop 10 times
        Client -> ServerQueue : msgget('server')
    end
    alt Failure
        Client -> User : "Server is not responding"
        'exit app
    else Sucessfull connection to server
        Client --> ServerQueue : msgsnd(client_id;client_seed;)
    end
else Sucessfull connection to server
    Client --> ServerQueue : msgsnd(client_id;client_seed;)
end


== Server Session ==
' Server receives client key and creates session
group Create session
    ServerQueue --> Server : msgrcv(client_id;client_seed;)
    create queue SessionQueue order 20
    Server -> SessionQueue : msgget(client_id;session_seed, IPC_CREAT)
    activate SessionQueue
    create Session order 21
    Server -> Session : fork()
    activate Session
    Session -> SessionQueue : msgget(client_id;session_seed)
    Session -> ClientQueue : msgget(client_id;client_seed;)
    Session --> ClientQueue : msgsnd(client_id;session_seed)
end
' Client receives session key and starts session and removes client queue
ClientQueue --> Client : msgrcv(client_id;session_seed)
Client -> SessionQueue : msgget(client_id;session_seed)
alt Failure connection to session
    loop 10 times
        Client -> SessionQueue : msgget(client_id;session_seed)
    end
    alt Failure
        Client -> User : "Server is not responding"
        'exit app
    end
else Sucessfull connection to session
    Client -> ClientQueue : msgctl(client_key, IPC_RMID)
    destroy ClientQueue
end