@startuml exitClient
!theme vibrant from https://raw.githubusercontent.com/plantuml/plantuml/master/themes


actor Bob as User
participant Client
queue SessionQueue
participant  Session
queue ServerQueue
participant Server
database ServerDB

autonumber

'we are already connected to the server
activate Session
activate SessionQueue
activate Server
activate ServerQueue
activate Client
User -> Client : exit
Client -> SessionQueue : logout
Client -> Client : status = offline
SessionQueue -> Session : exit
Session -> ServerQueue : exit(ClientID)
ServerQueue -> Server : exit(ClientID)
Server -> Server : status(ClientID) = offline
Server -> ServerDB : update status(ClientID) = offline
Server -> Server: propagate status to all friends
Server -> SessionQueue : close()
Server -> Server : update destroy(SessionID)
SessionQueue -> Session : close()
Session ->x SessionQueue : msgctl(SessionID, IPC_RMID)
destroy SessionQueue
Session ->x Session : return 0
destroy Session

Client ->x SessionQueue : close connection
Client ->x Client : close client
Client -> User : exit
destroy Client


@enduml
