@startuml loadClient
!theme vibrant from https://raw.githubusercontent.com/plantuml/plantuml/master/themes
autonumber

actor Bob as User
database ClientDB
participant Client
queue SessionQueue
participant  Session
queue ServerQueue
participant Server
database ServerDB


Client -> SessionQueue : msgsnd(loadData)
SessionQueue -> Session : msgrecv(loadData)
Session -> ServerQueue : msgsnd(loadData, ClientID)
ServerQueue -> Server : msgrecv(loadData, ClientID)
Server <-> ServerDB : loadData(ClientID)
Server -> Server : verifyData(data)
Server -> Server : checkUserStatus(data)

Server -> SessionQueue : msgsnd(data)
SessionQueue -> Session : msgrecv(data)
Session -> Session : change msg access rights()
Session -> SessionQueue : msgsnd(data)
SessionQueue -> Client : msgrecv(data)
Client -> Client : loadData(data)
Client <-> ClientDB : saveData(data)




@enduml
