#include "utils.h"

/**
 * It takes a string and returns a hash value.
 *
 * @param str The string to hash
 */
unsigned long hash(const char *str) {
	unsigned long hash = 5381;
	int c;

	while ((c = *str++)) hash = ((hash << 5) + hash) + c; /* hash * 33 + c */

	return hash;
}

/**
 * It takes a clientId and a sessionSeed and returns a sessionKey
 *
 * @param clientId The client ID of the client that is connecting to the server.
 * @param sessionSeed A random number generated by the client.
 *
 * @return The clientId and sessionSeed are being shifted 7 bits to the left and
 * then added together.
 */
int createSessonKey(int clientId, int sessionSeed) {
	return (clientId << 7) + sessionSeed;
}
