name: Generate PlantUML Diagrams
on:
  push:
#    paths:
#      - '**/**.puml'
    branches-ignore:
      - 'main'
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download PlantUML
        run: |
          wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar

      - name: Process Diagrams
        run: java -jar plantuml.jar -v -tsvg -r -o "${{ github.workspace }}/out" "diagrams/**.puml"
      - name: Display Diagrams
        run: pwd && ls out/** | grep \.svg$

      - name: Remove PlantUML
        run: rm plantuml.jar

      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "Generate SVG for PlantUML diagrams"
