name: Generate PlantUML Diagrams
on:
  push:
#    paths:
#      - '**/**.puml'
    branches-ignore:
      - 'main'
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get UML files
        id: getfile
        run: |
          echo 'FILES<<EOF' >> $GITHUB_OUTPUT
          find . -name '*.puml' >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg ${{ steps.getfile.outputs.FILES }}

      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "Generate SVG for PlantUML diagrams"
