name: Generate PlantUML Diagrams
on:
  push:
#    paths:
#      - '**/**.puml'
    branches-ignore:
      - 'main'
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download PlantUML
        run: |
          wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar

      - name: Process Diagrams
        run: java -jar plantuml.jar -v -tsvg -r -o "${{ github.workspace }}/out" "diagrams/**.puml"
      - name: Display Diagrams
        run: pwd && ls out/** | grep \.svg$

      - name: Remove PlantUML
        run: rm plantuml.jar

      - name: Setup GPG
        run: |
          echo ${{ secrets.GPG_PRIVATE_KEY }} | base64 --decode | gpg --import
          echo ${{ secrets.PASSPHRASE }} | gpg --passphrase-fd 0 --batch --yes --pinentry-mode loopback --import-ownertrust
          git config --global gpg.program gpg
          git config --global commit.gpgsign true
          git config --global user.signingkey ${{ secrets.GPG_KEY_ID }}



      - name: List keys
        run: |
          gpg -K
          gpg --list-secret-keys --keyid-format LONG
          gpg2 --list-secret-keys --keyid-format LONG


      - name: Commit Changes
        run: |
          git add out -f
          GIT_TRACE=1 git commit -S -m "Generate SVG for PlantUML diagrams"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


