name: Generate PlantUML Diagrams
on:
  push:
#    paths:
#      - '**/**.puml'
    branches-ignore:
      - 'main'
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download PlantUML
        run: |
          wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar

      - name: Process Diagrams
        run: java -jar plantuml.jar -v -tsvg -r -o "${{ github.workspace }}/out" "diagrams/**.puml"
      - name: Display Diagrams
        run: pwd && ls out/** | grep \.svg$

      - name: Remove PlantUML
        run: rm plantuml.jar

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --global user.signingkey $GPG_SIGNING_KEY
          git add out -f
          git commit -S -m "Generate SVG for PlantUML diagrams" -a

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


