name: Generate PlantUML Diagrams
on:
  push:
#    paths:
#      - '**/**.puml'
    branches-ignore:
      - 'main'
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download PlantUML
        run: |
          wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar

      - name: Process Diagrams
        run: java -jar plantuml.jar -v -tsvg -r -o "${{ github.workspace }}/out" "diagrams/**.puml"
      - name: Display Diagrams
        run: pwd && ls out/** | grep \.svg$

      - name: Remove PlantUML
        run: rm plantuml.jar

      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: true
          git_config_global: true


      - name: List keys
        run: |
          gpg -K
          gpg --list-secret-keys --keyid-format LONG
          gpg2 --list-secret-keys --keyid-format LONG


      - name: Commit Changes
        run: |
          git add out -f
          GIT_TRACE=1 git commit -S -m "Generate SVG for PlantUML diagrams"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


