name: generate plantuml
on: 
  push:
   branches-ignore:
     - "main"
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
      - name: Checkout Repository
        uses: actions/checkout@v3

        
      - name: Download PlantUML
        run: wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar
      - name: Process Diagrams
        run: java -jar plantuml.jar -v -tsvg -r -o "${{ github.workspace }}/out" "diagrams/**.puml"
      - name: Display Diagrams
        run: pwd && ls out
      - name: Remove PlantUML
        run: rm plantuml.jar


      - name: Import GPG private key with passphrase
        run: |
          echo ${{ secrets.GPG_PRIVATE_KEY }} | base64 --decode | gpg --import
          echo ${{ secrets.GPG_PASSPHRASE }} | base64 --decode | gpg --batch --passphrase-fd 0 --pinentry-mode loopback --import-ownertrust

      - name: Check if gpg exists
        run: gpg --version

      -
        name: List keys
        run: gpg --list-secret-keys --keyid-format LONG
      
      - name: Configure git based on GPG key imported above
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global user.signingkey ${{ secrets.GPG_KEY_ID }}
          git config --global commit.gpgsign true
          



      - name: Commit and Push
        run: |
          git add .
          git commit -S -m "Update diagrams [no ci]"
          git push


