name: generate plantuml
on: 
  push:
   branches-ignore:
     - "main"
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
      - name: Checkout Repository
        uses: actions/checkout@v3

        
      - name: Download PlantUML
        run: wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar
      - name: Process Diagrams
        run: java -jar plantuml.jar -v -tsvg -r -o "${{ github.workspace }}/out" "diagrams/**.puml"
      - name: Display Diagrams
        run: pwd && ls out
      - name: Remove PlantUML
        run: rm plantuml.jar


      - name: check if gpg exists
        run: gpg --version

      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit and Push
        run: |
          git add .
          git commit -S -m "Update diagrams [no ci]"
          git push


